### ISSUE TITLE
Autocomplete not working at new release on Windows

### ISSUE THREAD

**Issue by vladimir-kotikov** [SublimeCodeIntel/SublimeCodeIntel#315]
After updating to 2.0.4 (Sublime text 2.0.2) via package control got some errors:

* First:

    Exception AttributeError: "'ProcessOpen' object has no attribute '_child_created'" in <bound method ProcessOpen.__del__ of <process.ProcessOpen object at 0x06201270>> ignored

at Sublime text console.
I solve it by adding ```self._child_created = False``` to ```ProcessOpen.__init__``` at process.py

* Second, i still have some traceback in codeintel.log:

```
Starting logging SublimeCodeIntel v2.0.4 rev GIT-unknown (1379425884) on Tue Sep 17 18:18:12 2013
=================================================================================================
+ Debug: Invalid language: Plain text. Available: JavaScript, Mason, XBL, XUL, RHTML, SCSS, Python, HTML, Ruby, Python3, XML, Sass, XSLT, Django, HTML5, Perl, CSS, Twig, Less, Smarty, Node.js, Tcl, TemplateToolkit, PHP
+ Info: processing `Python': please wait...
New env with catalogs for 'Python': PyWin32
Updating indexes for 'Python'... The first time this can take a while.
scan_purelang: path: u'C:\\Users\\kotoff\\Dropbox\\Projects\\Python\\MudBase\\mudbase_search.py' lang: Python
Doing CodeIntel for 'Python' (hold on)...
done eval: success
error evaluating Python imports: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 12: ordinal not in range(128) (C:\Users\kotoff\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel\libs\process.py#280 in __init__)
error evaluating Python imports
Traceback (most recent call last):
  File "C:\Users\kotoff\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel\libs\codeintel2\manager.py", line 525, in run
    eval_sess.eval(self)
  File "C:\Users\kotoff\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel\libs\codeintel2\lang_python.py", line 272, in eval
    for lib in self.buf.libs:
  File "C:\Users\kotoff\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel\libs\codeintel2\lang_python.py", line 700, in libs
    return self.langintel.libs_from_buf(self)
  File "C:\Users\kotoff\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel\libs\codeintel2\lang_python.py", line 643, in libs_from_buf
    libs += self._buf_indep_libs_from_env(env)
  File "C:\Users\kotoff\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel\libs\codeintel2\lang_python.py", line 561, in _buf_indep_libs_from_env
    = self.python_info_from_env(env)
  File "C:\Users\kotoff\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel\libs\codeintel2\lang_python.py", line 543, in python_info_from_env
    info = self._python_info_from_python(python, env)
  File "C:\Users\kotoff\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel\libs\codeintel2\lang_python.py", line 433, in _python_info_from_python
    p = process.ProcessOpen(argv, env=env.get_all_envvars(), stdin=None)
  File "C:\Users\kotoff\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel\libs\process.py", line 280, in __init__
    _enc_env[key.encode(encoding)] = value.encode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 12: ordinal not in range(128)
Done 'Python' CodeIntel! Full CodeIntel took 57ms
done eval: unexpected eval error
```

Solved by adding 
```
except UnicodeDecodeError:
    # Could not encode it, warn we are dropping it.
    log.warn("Could not encode environment variable %r "
        "so removing it", key)
```
after _UnicodeEncodeError_

* Third: after all codeintel looks like working, but when i typing module name after ```import```, modules are shown, but not substituted: i'll show you screenshots:

![image](https://f.cloud.github.com/assets/3857604/1157669/973c303e-1fa5-11e3-8a28-900096486bf1.png)
after typing ```import``` list is shown

![image](https://f.cloud.github.com/assets/3857604/1157693/e230602e-1fa5-11e3-93c8-653ababc0dad.png)
when i started typing module name, list is disappeared

![image](https://f.cloud.github.com/assets/3857604/1157703/0cc8b2a0-1fa6-11e3-98b8-4c5837e8f843.png)
when i try to ```from module import```, it works fine.

log file looks ok

```
Starting logging SublimeCodeIntel v2.0.4 rev GIT-unknown (1379425884) on Tue Sep 17 18:22:29 2013
=================================================================================================
+ Debug: Invalid language: Plain text. Available: JavaScript, Mason, XBL, XUL, RHTML, SCSS, Python, HTML, Ruby, Python3, XML, Sass, XSLT, Django, HTML5, Perl, CSS, Twig, Less, Smarty, Node.js, Tcl, TemplateToolkit, PHP
+ Info: processing `Python': please wait...
New env with catalogs for 'Python': PyWin32
Updating indexes for 'Python'... The first time this can take a while.
scan_purelang: path: u'C:\\Users\\kotoff\\Dropbox\\Projects\\Python\\MudBase\\mudbase_search.py' lang: Python
Doing CodeIntel for 'Python' (hold on)...
scan_purelang: path: 'c:\\python27\\lib\\site-packages\\pip-1.4.1-py2.7.egg\\pip\\__init__.py' lang: Python
scan_purelang: path: 'c:\\python27\\lib\\site-packages\\lxml-3.2.3-py2.7-win32.egg\\lxml\\__init__.py' lang: Python
scan_purelang: path: 'c:\\python27\\lib\\site-packages\\BeautifulSoup.py' lang: Python
scan_purelang: path: 'c:\\python27\\lib\\site-packages\\BeautifulSoupTests.py' lang: Python
+ Event: Adding 'pywin32.cix' API catalog
+ Info: Doing CodeIntel for 'Python' (hold on)...
+ Event: Adding python-2.7 stdlib
done eval: success
Done 'Python' CodeIntel! Full CodeIntel took ~12s
Autocomplete called (Python) [cplns]
+ Info: processing `Python': please wait...
Updating indexes for 'Python'... The first time this can take a while.
scan_purelang: path: u'C:\\Users\\kotoff\\Dropbox\\Projects\\Python\\MudBase\\mudbase_search.py' lang: Python
Doing CodeIntel for 'Python' (hold on)...
done eval: success
Done 'Python' CodeIntel! Full CodeIntel took 9ms
Autocomplete called (Python) [cplns]
+ Info: processing `Python': please wait...
Doing CodeIntel for 'Python' (hold on)...
done eval: success
Done 'Python' CodeIntel! Full CodeIntel took 10ms
Autocomplete called (Python) [cplns]
+ Info: processing `Python': please wait...
Doing CodeIntel for 'Python' (hold on)...
done eval: success
Done 'Python' CodeIntel! Full CodeIntel took 7ms
Autocomplete called (Python) [cplns]
+ Info: processing `Python': please wait...
Doing CodeIntel for 'Python' (hold on)...
done eval: success
Done 'Python' CodeIntel! Full CodeIntel took 6ms
Autocomplete called (Python) [cplns]
+ Info: processing `Python': please wait...
Updating indexes for 'Python'... The first time this can take a while.
scan_purelang: path: u'C:\\Users\\kotoff\\Dropbox\\Projects\\Python\\MudBase\\mudbase_search.py' lang: Python
Doing CodeIntel for 'Python' (hold on)...
done eval: success
Done 'Python' CodeIntel! Full CodeIntel took 10ms
Autocomplete called (Python) [cplns]
Doing CodeIntel for 'Python' (hold on)...+
 Info: processing `Python': please wait...
done eval: success
Done 'Python' CodeIntel! Full CodeIntel took 45ms
+ Info: processing `Python': please wait...
Doing CodeIntel for 'Python' (hold on)...
done eval: success
Done 'Python' CodeIntel! Full CodeIntel took 7ms
Autocomplete called (Python) [cplns]
+ Info: processing `Python': please wait...
Doing CodeIntel for 'Python' (hold on)...
done eval: success
Done 'Python' CodeIntel! Full CodeIntel took 9ms
Autocomplete called (Python) [cplns]
+ Info: processing `Python': please wait...
Doing CodeIntel for 'Python' (hold on)...
done eval: success
Done 'Python' CodeIntel! Full CodeIntel took 9ms
Autocomplete called (Python) [cplns]
+ Info: processing `Python': please wait...
Doing CodeIntel for 'Python' (hold on)...
Done 'Python' CodeIntel! Full CodeIntel took 6ms
+ Info: processing `Python': please wait...
Updating indexes for 'Python'... The first time this can take a while.
scan_purelang: path: u'C:\\Users\\kotoff\\Dropbox\\Projects\\Python\\MudBase\\mudbase_search.py' lang: Python
Doing CodeIntel for 'Python' (hold on)...
Done 'Python' CodeIntel! Full CodeIntel took 39ms
+ Info: processing `Python': please wait...
Doing CodeIntel for 'Python' (hold on)...
Done 'Python' CodeIntel! Full CodeIntel took 3ms
```

My system is Win8 professional, x86, Sublime Text 2.0.2, Sublime Codeintel 2.0.4 and Python 2.7
